apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: labas-smk
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaybrain2015/Labas_smk
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: labas-smk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
