apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: labas-smk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jaybrain/labas-frontend:latest
          env:
            - name: VITE_API_URL
              value: "https://healthcare-appointments.com/api"
            - name: VITE_AI_URL
              value: "https://healthcare-appointments.com/ai"
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: labas-smk
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
