apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: labas-smk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: jaybrain/labas-nginx:dbbe97607ec1c0a72e8322fc10d30dc58006845f
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: labas-smk
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
