apiVersion: v1
kind: Secret
metadata:
  name: labas-secrets
  namespace: labas-smk
type: Opaque
stringData:
  DB_DATABASE: "${{ DB_DATABASE }}"
  DB_USERNAME: "${{ DB_USERNAME }}"
  DB_PASSWORD: "${{ DB_PASSWORD }}"
  APP_KEY: "${{ APP_KEY }}"
  ANTHROPIC_API_KEY: "${{ ANTHROPIC_API_KEY }}"

